[project]
name = "learning-geminiai"
version = "0.1.0"
description = "My first fastapi project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.2",
    "uvicorn>=0.38.0",
]
